// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6uYEs-BGXeY-scLo9SVI2gBAPgWKfOE',
    appId: '1:768963722307:web:b154eb2b54a9c0956268f6',
    messagingSenderId: '768963722307',
    projectId: 'app-dev-zia',
    authDomain: 'app-dev-zia.firebaseapp.com',
    storageBucket: 'app-dev-zia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_vkpGeR4QLgA0zvbJGdPnA5AveroAQc4',
    appId: '1:768963722307:android:0f14f2594cef3c066268f6',
    messagingSenderId: '768963722307',
    projectId: 'app-dev-zia',
    storageBucket: 'app-dev-zia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEInjZ3yXQDAM4Ux74O7wZIcwwgW5dwu0',
    appId: '1:768963722307:ios:a564fc5d1d8b54516268f6',
    messagingSenderId: '768963722307',
    projectId: 'app-dev-zia',
    storageBucket: 'app-dev-zia.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEInjZ3yXQDAM4Ux74O7wZIcwwgW5dwu0',
    appId: '1:768963722307:ios:a564fc5d1d8b54516268f6',
    messagingSenderId: '768963722307',
    projectId: 'app-dev-zia',
    storageBucket: 'app-dev-zia.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW6uYEs-BGXeY-scLo9SVI2gBAPgWKfOE',
    appId: '1:768963722307:web:04643c2b2e80ed166268f6',
    messagingSenderId: '768963722307',
    projectId: 'app-dev-zia',
    authDomain: 'app-dev-zia.firebaseapp.com',
    storageBucket: 'app-dev-zia.firebasestorage.app',
  );
}
